// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod zeus {

#[allow(unused_imports, dead_code)]
pub mod ghost {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_HANDOFF_TYPE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_HANDOFF_TYPE: i8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_HANDOFF_TYPE: [HandoffType; 3] = [
  HandoffType::Offer,
  HandoffType::Ack,
  HandoffType::Commit,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct HandoffType(pub i8);
#[allow(non_upper_case_globals)]
impl HandoffType {
  pub const Offer: Self = Self(0);
  pub const Ack: Self = Self(1);
  pub const Commit: Self = Self(2);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Offer,
    Self::Ack,
    Self::Commit,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Offer => Some("Offer"),
      Self::Ack => Some("Ack"),
      Self::Commit => Some("Commit"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for HandoffType {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for HandoffType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for HandoffType {
    type Output = HandoffType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for HandoffType {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for HandoffType {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for HandoffType {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_DISCOVERY_PAYLOAD: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_DISCOVERY_PAYLOAD: u8 = 4;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_DISCOVERY_PAYLOAD: [DiscoveryPayload; 5] = [
  DiscoveryPayload::NONE,
  DiscoveryPayload::DiscoveryAnnounce,
  DiscoveryPayload::DiscoveryFindNode,
  DiscoveryPayload::DiscoveryNodeInfo,
  DiscoveryPayload::DiscoveryHeartbeat,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct DiscoveryPayload(pub u8);
#[allow(non_upper_case_globals)]
impl DiscoveryPayload {
  pub const NONE: Self = Self(0);
  pub const DiscoveryAnnounce: Self = Self(1);
  pub const DiscoveryFindNode: Self = Self(2);
  pub const DiscoveryNodeInfo: Self = Self(3);
  pub const DiscoveryHeartbeat: Self = Self(4);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 4;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::DiscoveryAnnounce,
    Self::DiscoveryFindNode,
    Self::DiscoveryNodeInfo,
    Self::DiscoveryHeartbeat,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::DiscoveryAnnounce => Some("DiscoveryAnnounce"),
      Self::DiscoveryFindNode => Some("DiscoveryFindNode"),
      Self::DiscoveryNodeInfo => Some("DiscoveryNodeInfo"),
      Self::DiscoveryHeartbeat => Some("DiscoveryHeartbeat"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for DiscoveryPayload {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for DiscoveryPayload {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for DiscoveryPayload {
    type Output = DiscoveryPayload;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for DiscoveryPayload {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for DiscoveryPayload {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for DiscoveryPayload {}
pub struct DiscoveryPayloadUnionTableOffset {}

// struct Vec3, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Vec3(pub [u8; 12]);
impl Default for Vec3 { 
  fn default() -> Self { 
    Self([0; 12])
  }
}
impl ::core::fmt::Debug for Vec3 {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("Vec3")
      .field("x", &self.x())
      .field("y", &self.y())
      .field("z", &self.z())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Vec3 {}
impl<'a> ::flatbuffers::Follow<'a> for Vec3 {
  type Inner = &'a Vec3;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a Vec3>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a Vec3 {
  type Inner = &'a Vec3;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<Vec3>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for Vec3 {
    type Output = Vec3;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const Vec3 as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> ::flatbuffers::Verifiable for Vec3 {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Vec3 {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    x: f32,
    y: f32,
    z: f32,
  ) -> Self {
    let mut s = Self([0; 12]);
    s.set_x(x);
    s.set_y(y);
    s.set_z(z);
    s
  }

  pub fn x(&self) -> f32 {
    let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_x(&mut self, x: f32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn y(&self) -> f32 {
    let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_y(&mut self, x: f32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn z(&self) -> f32 {
    let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_z(&mut self, x: f32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

// struct NodeLoad, aligned to 2
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct NodeLoad(pub [u8; 4]);
impl Default for NodeLoad { 
  fn default() -> Self { 
    Self([0; 4])
  }
}
impl ::core::fmt::Debug for NodeLoad {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("NodeLoad")
      .field("entity_count", &self.entity_count())
      .field("cpu_percent", &self.cpu_percent())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for NodeLoad {}
impl<'a> ::flatbuffers::Follow<'a> for NodeLoad {
  type Inner = &'a NodeLoad;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a NodeLoad>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a NodeLoad {
  type Inner = &'a NodeLoad;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<NodeLoad>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for NodeLoad {
    type Output = NodeLoad;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const NodeLoad as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(2)
    }
}

impl<'a> ::flatbuffers::Verifiable for NodeLoad {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> NodeLoad {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    entity_count: u16,
    cpu_percent: u8,
  ) -> Self {
    let mut s = Self([0; 4]);
    s.set_entity_count(entity_count);
    s.set_cpu_percent(cpu_percent);
    s
  }

  pub fn entity_count(&self) -> u16 {
    let mut mem = ::core::mem::MaybeUninit::<<u16 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_entity_count(&mut self, x: u16) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn cpu_percent(&self) -> u8 {
    let mut mem = ::core::mem::MaybeUninit::<<u8 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[2..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_cpu_percent(&mut self, x: u8) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[2..].as_mut_ptr(),
        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum GhostOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Ghost<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Ghost<'a> {
  type Inner = Ghost<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Ghost<'a> {
  pub const VT_ENTITY_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_POSITION: ::flatbuffers::VOffsetT = 6;
  pub const VT_VELOCITY: ::flatbuffers::VOffsetT = 8;
  pub const VT_SIGNATURE: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Ghost { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GhostArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Ghost<'bldr>> {
    let mut builder = GhostBuilder::new(_fbb);
    builder.add_entity_id(args.entity_id);
    if let Some(x) = args.signature { builder.add_signature(x); }
    if let Some(x) = args.velocity { builder.add_velocity(x); }
    if let Some(x) = args.position { builder.add_position(x); }
    builder.finish()
  }


  #[inline]
  pub fn entity_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Ghost::VT_ENTITY_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn position(&self) -> Option<&'a Vec3> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Vec3>(Ghost::VT_POSITION, None)}
  }
  #[inline]
  pub fn velocity(&self) -> Option<&'a Vec3> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Vec3>(Ghost::VT_VELOCITY, None)}
  }
  #[inline]
  pub fn signature(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Ghost::VT_SIGNATURE, None)}
  }
}

impl ::flatbuffers::Verifiable for Ghost<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("entity_id", Self::VT_ENTITY_ID, false)?
     .visit_field::<Vec3>("position", Self::VT_POSITION, false)?
     .visit_field::<Vec3>("velocity", Self::VT_VELOCITY, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("signature", Self::VT_SIGNATURE, false)?
     .finish();
    Ok(())
  }
}
pub struct GhostArgs<'a> {
    pub entity_id: u64,
    pub position: Option<&'a Vec3>,
    pub velocity: Option<&'a Vec3>,
    pub signature: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for GhostArgs<'a> {
  #[inline]
  fn default() -> Self {
    GhostArgs {
      entity_id: 0,
      position: None,
      velocity: None,
      signature: None,
    }
  }
}

pub struct GhostBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GhostBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_entity_id(&mut self, entity_id: u64) {
    self.fbb_.push_slot::<u64>(Ghost::VT_ENTITY_ID, entity_id, 0);
  }
  #[inline]
  pub fn add_position(&mut self, position: &Vec3) {
    self.fbb_.push_slot_always::<&Vec3>(Ghost::VT_POSITION, position);
  }
  #[inline]
  pub fn add_velocity(&mut self, velocity: &Vec3) {
    self.fbb_.push_slot_always::<&Vec3>(Ghost::VT_VELOCITY, velocity);
  }
  #[inline]
  pub fn add_signature(&mut self, signature: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Ghost::VT_SIGNATURE, signature);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GhostBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GhostBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Ghost<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Ghost<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Ghost");
      ds.field("entity_id", &self.entity_id());
      ds.field("position", &self.position());
      ds.field("velocity", &self.velocity());
      ds.field("signature", &self.signature());
      ds.finish()
  }
}
pub enum HandoffMsgOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct HandoffMsg<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for HandoffMsg<'a> {
  type Inner = HandoffMsg<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> HandoffMsg<'a> {
  pub const VT_ENTITY_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_TYPE_: ::flatbuffers::VOffsetT = 6;
  pub const VT_STATE: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    HandoffMsg { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args HandoffMsgArgs<'args>
  ) -> ::flatbuffers::WIPOffset<HandoffMsg<'bldr>> {
    let mut builder = HandoffMsgBuilder::new(_fbb);
    builder.add_entity_id(args.entity_id);
    if let Some(x) = args.state { builder.add_state(x); }
    builder.add_type_(args.type_);
    builder.finish()
  }


  #[inline]
  pub fn entity_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(HandoffMsg::VT_ENTITY_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn type_(&self) -> HandoffType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<HandoffType>(HandoffMsg::VT_TYPE_, Some(HandoffType::Offer)).unwrap()}
  }
  #[inline]
  pub fn state(&self) -> Option<Ghost<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Ghost>>(HandoffMsg::VT_STATE, None)}
  }
}

impl ::flatbuffers::Verifiable for HandoffMsg<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("entity_id", Self::VT_ENTITY_ID, false)?
     .visit_field::<HandoffType>("type_", Self::VT_TYPE_, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Ghost>>("state", Self::VT_STATE, false)?
     .finish();
    Ok(())
  }
}
pub struct HandoffMsgArgs<'a> {
    pub entity_id: u64,
    pub type_: HandoffType,
    pub state: Option<::flatbuffers::WIPOffset<Ghost<'a>>>,
}
impl<'a> Default for HandoffMsgArgs<'a> {
  #[inline]
  fn default() -> Self {
    HandoffMsgArgs {
      entity_id: 0,
      type_: HandoffType::Offer,
      state: None,
    }
  }
}

pub struct HandoffMsgBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> HandoffMsgBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_entity_id(&mut self, entity_id: u64) {
    self.fbb_.push_slot::<u64>(HandoffMsg::VT_ENTITY_ID, entity_id, 0);
  }
  #[inline]
  pub fn add_type_(&mut self, type_: HandoffType) {
    self.fbb_.push_slot::<HandoffType>(HandoffMsg::VT_TYPE_, type_, HandoffType::Offer);
  }
  #[inline]
  pub fn add_state(&mut self, state: ::flatbuffers::WIPOffset<Ghost<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Ghost>>(HandoffMsg::VT_STATE, state);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> HandoffMsgBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    HandoffMsgBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<HandoffMsg<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for HandoffMsg<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("HandoffMsg");
      ds.field("entity_id", &self.entity_id());
      ds.field("type_", &self.type_());
      ds.field("state", &self.state());
      ds.finish()
  }
}
pub enum DiscoveryAnnounceOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DiscoveryAnnounce<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DiscoveryAnnounce<'a> {
  type Inner = DiscoveryAnnounce<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DiscoveryAnnounce<'a> {
  pub const VT_NODE_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_ADDRESS: ::flatbuffers::VOffsetT = 6;
  pub const VT_POSITION: ::flatbuffers::VOffsetT = 8;
  pub const VT_LOAD: ::flatbuffers::VOffsetT = 10;
  pub const VT_KNOWN_NODE_IDS: ::flatbuffers::VOffsetT = 12;
  pub const VT_ORDINAL: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DiscoveryAnnounce { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DiscoveryAnnounceArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DiscoveryAnnounce<'bldr>> {
    let mut builder = DiscoveryAnnounceBuilder::new(_fbb);
    builder.add_node_id(args.node_id);
    builder.add_ordinal(args.ordinal);
    if let Some(x) = args.known_node_ids { builder.add_known_node_ids(x); }
    if let Some(x) = args.load { builder.add_load(x); }
    if let Some(x) = args.position { builder.add_position(x); }
    if let Some(x) = args.address { builder.add_address(x); }
    builder.finish()
  }


  #[inline]
  pub fn node_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DiscoveryAnnounce::VT_NODE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn address(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DiscoveryAnnounce::VT_ADDRESS, None)}
  }
  #[inline]
  pub fn position(&self) -> Option<&'a Vec3> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Vec3>(DiscoveryAnnounce::VT_POSITION, None)}
  }
  #[inline]
  pub fn load(&self) -> Option<&'a NodeLoad> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<NodeLoad>(DiscoveryAnnounce::VT_LOAD, None)}
  }
  #[inline]
  pub fn known_node_ids(&self) -> Option<::flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u64>>>(DiscoveryAnnounce::VT_KNOWN_NODE_IDS, None)}
  }
  #[inline]
  pub fn ordinal(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(DiscoveryAnnounce::VT_ORDINAL, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for DiscoveryAnnounce<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("node_id", Self::VT_NODE_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("address", Self::VT_ADDRESS, false)?
     .visit_field::<Vec3>("position", Self::VT_POSITION, false)?
     .visit_field::<NodeLoad>("load", Self::VT_LOAD, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u64>>>("known_node_ids", Self::VT_KNOWN_NODE_IDS, false)?
     .visit_field::<u32>("ordinal", Self::VT_ORDINAL, false)?
     .finish();
    Ok(())
  }
}
pub struct DiscoveryAnnounceArgs<'a> {
    pub node_id: u64,
    pub address: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub position: Option<&'a Vec3>,
    pub load: Option<&'a NodeLoad>,
    pub known_node_ids: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u64>>>,
    pub ordinal: u32,
}
impl<'a> Default for DiscoveryAnnounceArgs<'a> {
  #[inline]
  fn default() -> Self {
    DiscoveryAnnounceArgs {
      node_id: 0,
      address: None,
      position: None,
      load: None,
      known_node_ids: None,
      ordinal: 0,
    }
  }
}

pub struct DiscoveryAnnounceBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DiscoveryAnnounceBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_node_id(&mut self, node_id: u64) {
    self.fbb_.push_slot::<u64>(DiscoveryAnnounce::VT_NODE_ID, node_id, 0);
  }
  #[inline]
  pub fn add_address(&mut self, address: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DiscoveryAnnounce::VT_ADDRESS, address);
  }
  #[inline]
  pub fn add_position(&mut self, position: &Vec3) {
    self.fbb_.push_slot_always::<&Vec3>(DiscoveryAnnounce::VT_POSITION, position);
  }
  #[inline]
  pub fn add_load(&mut self, load: &NodeLoad) {
    self.fbb_.push_slot_always::<&NodeLoad>(DiscoveryAnnounce::VT_LOAD, load);
  }
  #[inline]
  pub fn add_known_node_ids(&mut self, known_node_ids: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DiscoveryAnnounce::VT_KNOWN_NODE_IDS, known_node_ids);
  }
  #[inline]
  pub fn add_ordinal(&mut self, ordinal: u32) {
    self.fbb_.push_slot::<u32>(DiscoveryAnnounce::VT_ORDINAL, ordinal, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DiscoveryAnnounceBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DiscoveryAnnounceBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DiscoveryAnnounce<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DiscoveryAnnounce<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DiscoveryAnnounce");
      ds.field("node_id", &self.node_id());
      ds.field("address", &self.address());
      ds.field("position", &self.position());
      ds.field("load", &self.load());
      ds.field("known_node_ids", &self.known_node_ids());
      ds.field("ordinal", &self.ordinal());
      ds.finish()
  }
}
pub enum DiscoveryFindNodeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DiscoveryFindNode<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DiscoveryFindNode<'a> {
  type Inner = DiscoveryFindNode<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DiscoveryFindNode<'a> {
  pub const VT_SENDER_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_SEARCH_POS: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DiscoveryFindNode { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DiscoveryFindNodeArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DiscoveryFindNode<'bldr>> {
    let mut builder = DiscoveryFindNodeBuilder::new(_fbb);
    builder.add_sender_id(args.sender_id);
    if let Some(x) = args.search_pos { builder.add_search_pos(x); }
    builder.finish()
  }


  #[inline]
  pub fn sender_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DiscoveryFindNode::VT_SENDER_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn search_pos(&self) -> Option<&'a Vec3> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Vec3>(DiscoveryFindNode::VT_SEARCH_POS, None)}
  }
}

impl ::flatbuffers::Verifiable for DiscoveryFindNode<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("sender_id", Self::VT_SENDER_ID, false)?
     .visit_field::<Vec3>("search_pos", Self::VT_SEARCH_POS, false)?
     .finish();
    Ok(())
  }
}
pub struct DiscoveryFindNodeArgs<'a> {
    pub sender_id: u64,
    pub search_pos: Option<&'a Vec3>,
}
impl<'a> Default for DiscoveryFindNodeArgs<'a> {
  #[inline]
  fn default() -> Self {
    DiscoveryFindNodeArgs {
      sender_id: 0,
      search_pos: None,
    }
  }
}

pub struct DiscoveryFindNodeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DiscoveryFindNodeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_sender_id(&mut self, sender_id: u64) {
    self.fbb_.push_slot::<u64>(DiscoveryFindNode::VT_SENDER_ID, sender_id, 0);
  }
  #[inline]
  pub fn add_search_pos(&mut self, search_pos: &Vec3) {
    self.fbb_.push_slot_always::<&Vec3>(DiscoveryFindNode::VT_SEARCH_POS, search_pos);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DiscoveryFindNodeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DiscoveryFindNodeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DiscoveryFindNode<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DiscoveryFindNode<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DiscoveryFindNode");
      ds.field("sender_id", &self.sender_id());
      ds.field("search_pos", &self.search_pos());
      ds.finish()
  }
}
pub enum DiscoveryNodeInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DiscoveryNodeInfo<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DiscoveryNodeInfo<'a> {
  type Inner = DiscoveryNodeInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DiscoveryNodeInfo<'a> {
  pub const VT_NODE_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_ADDRESS: ::flatbuffers::VOffsetT = 6;
  pub const VT_POSITION: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DiscoveryNodeInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DiscoveryNodeInfoArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DiscoveryNodeInfo<'bldr>> {
    let mut builder = DiscoveryNodeInfoBuilder::new(_fbb);
    builder.add_node_id(args.node_id);
    if let Some(x) = args.position { builder.add_position(x); }
    if let Some(x) = args.address { builder.add_address(x); }
    builder.finish()
  }


  #[inline]
  pub fn node_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DiscoveryNodeInfo::VT_NODE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn address(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DiscoveryNodeInfo::VT_ADDRESS, None)}
  }
  #[inline]
  pub fn position(&self) -> Option<&'a Vec3> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Vec3>(DiscoveryNodeInfo::VT_POSITION, None)}
  }
}

impl ::flatbuffers::Verifiable for DiscoveryNodeInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("node_id", Self::VT_NODE_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("address", Self::VT_ADDRESS, false)?
     .visit_field::<Vec3>("position", Self::VT_POSITION, false)?
     .finish();
    Ok(())
  }
}
pub struct DiscoveryNodeInfoArgs<'a> {
    pub node_id: u64,
    pub address: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub position: Option<&'a Vec3>,
}
impl<'a> Default for DiscoveryNodeInfoArgs<'a> {
  #[inline]
  fn default() -> Self {
    DiscoveryNodeInfoArgs {
      node_id: 0,
      address: None,
      position: None,
    }
  }
}

pub struct DiscoveryNodeInfoBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DiscoveryNodeInfoBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_node_id(&mut self, node_id: u64) {
    self.fbb_.push_slot::<u64>(DiscoveryNodeInfo::VT_NODE_ID, node_id, 0);
  }
  #[inline]
  pub fn add_address(&mut self, address: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DiscoveryNodeInfo::VT_ADDRESS, address);
  }
  #[inline]
  pub fn add_position(&mut self, position: &Vec3) {
    self.fbb_.push_slot_always::<&Vec3>(DiscoveryNodeInfo::VT_POSITION, position);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DiscoveryNodeInfoBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DiscoveryNodeInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DiscoveryNodeInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DiscoveryNodeInfo<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DiscoveryNodeInfo");
      ds.field("node_id", &self.node_id());
      ds.field("address", &self.address());
      ds.field("position", &self.position());
      ds.finish()
  }
}
pub enum DiscoveryHeartbeatOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DiscoveryHeartbeat<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DiscoveryHeartbeat<'a> {
  type Inner = DiscoveryHeartbeat<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DiscoveryHeartbeat<'a> {
  pub const VT_SENDER_ID: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DiscoveryHeartbeat { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DiscoveryHeartbeatArgs
  ) -> ::flatbuffers::WIPOffset<DiscoveryHeartbeat<'bldr>> {
    let mut builder = DiscoveryHeartbeatBuilder::new(_fbb);
    builder.add_sender_id(args.sender_id);
    builder.finish()
  }


  #[inline]
  pub fn sender_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DiscoveryHeartbeat::VT_SENDER_ID, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for DiscoveryHeartbeat<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("sender_id", Self::VT_SENDER_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct DiscoveryHeartbeatArgs {
    pub sender_id: u64,
}
impl<'a> Default for DiscoveryHeartbeatArgs {
  #[inline]
  fn default() -> Self {
    DiscoveryHeartbeatArgs {
      sender_id: 0,
    }
  }
}

pub struct DiscoveryHeartbeatBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DiscoveryHeartbeatBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_sender_id(&mut self, sender_id: u64) {
    self.fbb_.push_slot::<u64>(DiscoveryHeartbeat::VT_SENDER_ID, sender_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DiscoveryHeartbeatBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DiscoveryHeartbeatBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DiscoveryHeartbeat<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DiscoveryHeartbeat<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DiscoveryHeartbeat");
      ds.field("sender_id", &self.sender_id());
      ds.finish()
  }
}
pub enum DiscoveryMsgOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DiscoveryMsg<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DiscoveryMsg<'a> {
  type Inner = DiscoveryMsg<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DiscoveryMsg<'a> {
  pub const VT_PAYLOAD_TYPE: ::flatbuffers::VOffsetT = 4;
  pub const VT_PAYLOAD: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DiscoveryMsg { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DiscoveryMsgArgs
  ) -> ::flatbuffers::WIPOffset<DiscoveryMsg<'bldr>> {
    let mut builder = DiscoveryMsgBuilder::new(_fbb);
    if let Some(x) = args.payload { builder.add_payload(x); }
    builder.add_payload_type(args.payload_type);
    builder.finish()
  }


  #[inline]
  pub fn payload_type(&self) -> DiscoveryPayload {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<DiscoveryPayload>(DiscoveryMsg::VT_PAYLOAD_TYPE, Some(DiscoveryPayload::NONE)).unwrap()}
  }
  #[inline]
  pub fn payload(&self) -> Option<::flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(DiscoveryMsg::VT_PAYLOAD, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_discovery_announce(&self) -> Option<DiscoveryAnnounce<'a>> {
    if self.payload_type() == DiscoveryPayload::DiscoveryAnnounce {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { DiscoveryAnnounce::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_discovery_find_node(&self) -> Option<DiscoveryFindNode<'a>> {
    if self.payload_type() == DiscoveryPayload::DiscoveryFindNode {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { DiscoveryFindNode::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_discovery_node_info(&self) -> Option<DiscoveryNodeInfo<'a>> {
    if self.payload_type() == DiscoveryPayload::DiscoveryNodeInfo {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { DiscoveryNodeInfo::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_discovery_heartbeat(&self) -> Option<DiscoveryHeartbeat<'a>> {
    if self.payload_type() == DiscoveryPayload::DiscoveryHeartbeat {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { DiscoveryHeartbeat::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for DiscoveryMsg<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_union::<DiscoveryPayload, _>("payload_type", Self::VT_PAYLOAD_TYPE, "payload", Self::VT_PAYLOAD, false, |key, v, pos| {
        match key {
          DiscoveryPayload::DiscoveryAnnounce => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<DiscoveryAnnounce>>("DiscoveryPayload::DiscoveryAnnounce", pos),
          DiscoveryPayload::DiscoveryFindNode => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<DiscoveryFindNode>>("DiscoveryPayload::DiscoveryFindNode", pos),
          DiscoveryPayload::DiscoveryNodeInfo => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<DiscoveryNodeInfo>>("DiscoveryPayload::DiscoveryNodeInfo", pos),
          DiscoveryPayload::DiscoveryHeartbeat => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<DiscoveryHeartbeat>>("DiscoveryPayload::DiscoveryHeartbeat", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct DiscoveryMsgArgs {
    pub payload_type: DiscoveryPayload,
    pub payload: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for DiscoveryMsgArgs {
  #[inline]
  fn default() -> Self {
    DiscoveryMsgArgs {
      payload_type: DiscoveryPayload::NONE,
      payload: None,
    }
  }
}

pub struct DiscoveryMsgBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DiscoveryMsgBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_payload_type(&mut self, payload_type: DiscoveryPayload) {
    self.fbb_.push_slot::<DiscoveryPayload>(DiscoveryMsg::VT_PAYLOAD_TYPE, payload_type, DiscoveryPayload::NONE);
  }
  #[inline]
  pub fn add_payload(&mut self, payload: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DiscoveryMsg::VT_PAYLOAD, payload);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DiscoveryMsgBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DiscoveryMsgBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DiscoveryMsg<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DiscoveryMsg<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DiscoveryMsg");
      ds.field("payload_type", &self.payload_type());
      match self.payload_type() {
        DiscoveryPayload::DiscoveryAnnounce => {
          if let Some(x) = self.payload_as_discovery_announce() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        DiscoveryPayload::DiscoveryFindNode => {
          if let Some(x) = self.payload_as_discovery_find_node() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        DiscoveryPayload::DiscoveryNodeInfo => {
          if let Some(x) = self.payload_as_discovery_node_info() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        DiscoveryPayload::DiscoveryHeartbeat => {
          if let Some(x) = self.payload_as_discovery_heartbeat() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("payload", &x)
        },
      };
      ds.finish()
  }
}
pub enum StateUpdateOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct StateUpdate<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for StateUpdate<'a> {
  type Inner = StateUpdate<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> StateUpdate<'a> {
  pub const VT_GHOSTS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    StateUpdate { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args StateUpdateArgs<'args>
  ) -> ::flatbuffers::WIPOffset<StateUpdate<'bldr>> {
    let mut builder = StateUpdateBuilder::new(_fbb);
    if let Some(x) = args.ghosts { builder.add_ghosts(x); }
    builder.finish()
  }


  #[inline]
  pub fn ghosts(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Ghost<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Ghost>>>>(StateUpdate::VT_GHOSTS, None)}
  }
}

impl ::flatbuffers::Verifiable for StateUpdate<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Ghost>>>>("ghosts", Self::VT_GHOSTS, false)?
     .finish();
    Ok(())
  }
}
pub struct StateUpdateArgs<'a> {
    pub ghosts: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Ghost<'a>>>>>,
}
impl<'a> Default for StateUpdateArgs<'a> {
  #[inline]
  fn default() -> Self {
    StateUpdateArgs {
      ghosts: None,
    }
  }
}

pub struct StateUpdateBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> StateUpdateBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ghosts(&mut self, ghosts: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Ghost<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(StateUpdate::VT_GHOSTS, ghosts);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> StateUpdateBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    StateUpdateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<StateUpdate<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for StateUpdate<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("StateUpdate");
      ds.field("ghosts", &self.ghosts());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Ghost`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_ghost_unchecked`.
pub fn root_as_ghost(buf: &[u8]) -> Result<Ghost<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Ghost>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Ghost` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_ghost_unchecked`.
pub fn size_prefixed_root_as_ghost(buf: &[u8]) -> Result<Ghost<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Ghost>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Ghost` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_ghost_unchecked`.
pub fn root_as_ghost_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Ghost<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Ghost<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Ghost` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_ghost_unchecked`.
pub fn size_prefixed_root_as_ghost_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Ghost<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Ghost<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Ghost and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Ghost`.
pub unsafe fn root_as_ghost_unchecked(buf: &[u8]) -> Ghost<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Ghost>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Ghost and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Ghost`.
pub unsafe fn size_prefixed_root_as_ghost_unchecked(buf: &[u8]) -> Ghost<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Ghost>(buf) }
}
#[inline]
pub fn finish_ghost_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Ghost<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_ghost_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Ghost<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod ghost
}  // pub mod zeus

