[package]
name = "zeus_orchestrator"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "zeus_orchestrator"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
quinn = "0.11.9"
tokio = { version = "1.49.0", features = ["full"] }
zeus_common = { version = "0.1.0", path = "../zeus_common" }
zeus_node = { version = "0.1.0", path = "../zeus_node" }
zeus_transport = { version = "0.1.0", path = "../zeus_transport" }

[dev-dependencies]
zeus_client = { version = "0.1.0", path = "../zeus_client" }
